export default {
  title: [
    {
      title: '序号',
      dataIndex: 'ID',
      key: 'ID',
    },
    {
      title: '工程名称',
      dataIndex: 'PROJECT_NAME',
      key: 'PROJECT_NAME',
    },
    {
      title: '所属组织',
      dataIndex: 'ORG_NAME',
      key: 'ORG_NAME',
    },
    {
      title: '设备状态',
      dataIndex: 'DEVICE_STATE',
      key: 'DEVICE_STATE',
    },
    {
      title: '当前设备数',
      dataIndex: 'DEVICECOUNT',
      key: 'DEVICECOUNT',
    },
    {
      title: '当前驾驶员数',
      dataIndex: 'OPERATORCOUNT',
      key: 'OPERATORCOUNT',
    },
    {
      title: '开始时间',
      dataIndex: 'START_TIME',
      key: 'START_TIME',
    },
    {
      title: '结束时间',
      dataIndex: 'END_TIME',
      key: 'END_TIME',
    },
    {
      title: '工程状态',
      dataIndex: 'PROJECT_STATE',
      key: 'PROJECT_STATE',
    },
    {
      title: '工程进度',
      dataIndex: 'PROJECT_PROGRESS',
      key: 'PROJECT_PROGRESS',
    },
  ],
  action: [
    {
      title: '操作',
      key: 'action',
    },
  ],
  data: {
    code: '1000',
    message: '操作成功',
    rows: [
      {
        ORG_ID: '3',
        START_TIME: '2021-12-01',
        PROJECT_STATE: 3,
        COUNTY_NAME: '',
        DEVICECOUNT: 1,
        PROVINCE_CODE: '',
        SY_CREATEUSERNAME: '许愿',
        PROJECT_NAME: '测试111',
        WORKING_TOTAL: 6158.59,
        PROJECT_PROGRESS: 1083.33,
        END_TIME: '2021-12-31',
        PROJECT_LEADER: '勇哥',
        ID: 'df792f42-e3d2-4c1e-8821-083f936ef755',
        COUNTY_CODE: '',
        DEVICE_STATE: 1,
        CITY_CODE: '',
        IDLE_WORKING_TIME: 0.0,
        OIL_CONSUMPTION: 69729.0,
        SY_CREATEUSERID: 'vM5pBvpntw8yz5OEcsa457~47SEB09',
        OPERATORCOUNT: 1,
        ORG_NAME: '测试机构',
        DEL_FLAG: 0,
        TOTAL_TIME: 1789.48,
        SY_AUDFLAG: 'NOSTATUS',
        PROJECT_CODE: 'df792f42-e3d2-4c1e-8826-083f936ef755',
        SY_PIID: '',
        PROVINCE_NAME: '',
        SY_PDID: '',
        SY_CREATEUSER: '258VK8rG21A',
        CITY_NAME: '',
        ADDRESS: '湖南省长沙市长沙县星沙街道三一重工治安执勤室三一重工产业园',
        LATITUDE: '113.097,28.24094',
      },
      {
        ORG_ID: '3',
        START_TIME: '2021-12-01',
        PROJECT_STATE: 2,
        COUNTY_NAME: '',
        DEVICECOUNT: 1,
        PROVINCE_CODE: '',
        SY_CREATEUSERNAME: '许愿',
        PROJECT_NAME: '测试222',
        WORKING_TOTAL: 1158.59,
        PROJECT_PROGRESS: 50.33,
        END_TIME: '2021-12-31',
        PROJECT_LEADER: '勇哥',
        ID: 'df792f42-e3d2-4c1e-8822-083f936ef755',
        COUNTY_CODE: '',
        DEVICE_STATE: 2,
        CITY_CODE: '',
        IDLE_WORKING_TIME: 0.0,
        OIL_CONSUMPTION: 69729.0,
        SY_CREATEUSERID: 'vM5pBvpntw8yz5OEcsa457~47SEB09',
        OPERATORCOUNT: 1,
        ORG_NAME: '测试机构',
        DEL_FLAG: 0,
        TOTAL_TIME: 2789.48,
        SY_AUDFLAG: 'NOSTATUS',
        PROJECT_CODE: 'df792f42-e3d2-4c1e-8826-083f936ef755',
        SY_PIID: '',
        PROVINCE_NAME: '',
        SY_PDID: '',
        SY_CREATEUSER: '258VK8rG21A',
        CITY_NAME: '',
        ADDRESS: '湖南省长沙市长沙县星沙街道三一重工治安执勤室三一重工产业园',
        LATITUDE: '113.097,28.24094',
      },
      {
        ORG_ID: '3',
        START_TIME: '2021-12-01',
        PROJECT_STATE: 1,
        COUNTY_NAME: '',
        DEVICECOUNT: 1,
        PROVINCE_CODE: '',
        SY_CREATEUSERNAME: '许愿',
        PROJECT_NAME: '测试333',
        WORKING_TOTAL: 6158.59,
        PROJECT_PROGRESS: 403.33,
        END_TIME: '2021-12-31',
        PROJECT_LEADER: '勇哥',
        ID: 'df792f42-e3d2-4c1e-8826-083f936ef755',
        COUNTY_CODE: '',
        DEVICE_STATE: 3,
        CITY_CODE: '',
        IDLE_WORKING_TIME: 0.0,
        OIL_CONSUMPTION: 69729.0,
        SY_CREATEUSERID: 'vM5pBvpntw8yz5OEcsa457~47SEB09',
        OPERATORCOUNT: 1,
        ORG_NAME: '测试机构',
        DEL_FLAG: 0,
        TOTAL_TIME: 1789.48,
        SY_AUDFLAG: 'NOSTATUS',
        PROJECT_CODE: 'df792f42-e3d2-4c1e-8826-083f936ef755',
        SY_PIID: '',
        PROVINCE_NAME: '',
        SY_PDID: '',
        SY_CREATEUSER: '258VK8rG21A',
        CITY_NAME: '',
        ADDRESS: '湖南省长沙市长沙县星沙街道三一重工治安执勤室三一重工产业园',
        LATITUDE: '113.097,28.24094',
      },
    ],
    success: true,
    totalCount: 1,
  },
};
